[package]
name = "mother"
version = "0.1.0"
edition = "2021"
authors = ["tomoikey"]
description = "A tool for generating Mother2 textboxes"

[dependencies]
ab_glyph = "0.2.29"
anyhow = "1.0.94"
clap = { version = "4.5.23", features = ["derive"] }
image = "0.25.5"
imageproc = "0.25.0"
open = "5.3.3"